# Generated by Django 5.1.5 on 2025-02-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0007_contactmessage_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('testimonial_text', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
