# Generated by Django 5.1.5 on 2025-02-10 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='applied_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
