# Generated by Django 5.1.5 on 2025-02-10 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_jobapplication_applied_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='cover_letter',
        ),
    ]
